package com.mowalk.app.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006C4C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF89F8C7)
val secondaryLight = Color(0xFF4B6558)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCEE7D9)
val tertiaryLight = Color(0xFF396A6B)
val onTertiaryLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFDFDF8)
val onBackgroundLight = Color(0xFF1A1C1A)
val surfaceLight = Color(0xFFFDFDF8)
val onSurfaceLight = Color(0xFF1A1C1A)
val surfaceVariantLight = Color(0xFFDFE4DB)
val onSurfaceVariantLight = Color(0xFF434841)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)

val primaryDark = Color(0xFF6CDB91)
val onPrimaryDark = Color(0xFF003D28)
val primaryContainerDark = Color(0xFF00533A)
val secondaryDark = Color(0xFFB2CBDC)
val onSecondaryDark = Color(0xFF233D32)
val secondaryContainerDark = Color(0xFF395448)
val tertiaryDark = Color(0xFF96D0D1)
val onTertiaryDark = Color(0xFF024041)
val backgroundDark = Color(0xFF1A1C1A)
val onBackgroundDark = Color(0xFFE3E3DE)
val surfaceDark = Color(0xFF1A1C1A)
val onSurfaceDark = Color(0xFFE3E3DE)
val surfaceVariantDark = Color(0xFF434841)
val onSurfaceVariantDark = Color(0xFFC3C8BF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)

val stepGreen = Color(0xFF4CAF50)
val stepGreenDark = Color(0xFF2E7D32)
val stepAmber = Color(0xFFFFC107)
val stepAmberDark = Color(0xFFFF8F00)
